# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

# Travis can cache content between builds. This speeds up the build process and saves resources.
# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# Defines all jobs which Travis will run in parallel.
jobs:
  # With fast finishing enabled, Travis CI will mark your build as finished as soon as one of two
  # conditions are met: The only remaining jobs are allowed to fail, or a job has already failed. In
  # these cases, the status of the build can already be determined, so there’s no need to wait around
  fast_finish: true

branches:
  only:
    - main

script:
  - make test
