name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
    - name: Coursier cache
      uses: coursier/cache-action@v5

    - name: Build and Test
      run: |
        make test
        sudo rm -rf "$HOME/.ivy2/local" || true
        sudo find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        sudo find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        sudo find $HOME/.sbt                              -name "*.lock"               -delete || true
